version: '3.8'
services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '83:81'
      - '443:443'
    volumes:
      - ./data_npm:/data
      - ./letsencrypt:/etc/letsencrypt
    restart: always
    environment:
      X_FRAME_OPTIONS: "sameorigin"
      DB_SQLITE_FILE: "/data/database.sqlite"
      TZ: "Europe/London"
      PUID: "${UID}"
      PGID: "${GID}"
    networks:
      - service_vnet

  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    network_mode: "host"
    environment:
      PUID: "${UID}"
      PGID: "${GID}"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true
    volumes:
      - ./data_f2b:/data
      - ./data_npm/logs/:/var/log/npm/:ro
    restart: always
    env_file:
      - ./fail2ban.env
    depends_on:
      - nginx-proxy-manager

networks:
  service_vnet:
    name: proxy_vnet
    external: true
